---
# tasks file for appserver

- include_role: 
    name: geerlingguy.nodejs

- name: Install Git
  apt:
    name: 'git'
    state: latest

- name: Install global npm packages
  npm:
    name: pm2
    global: yes

- name: Create Folders
  file:
    dest: '{{ app_path }}'
    mode: 0755
    recurse: yes
    state: directory

- name: Clone the application
  git:
    repo: https://github.com/TobiasMende/MetaNook2018-Ansible-App.git
    dest: '{{ app_path }}'
    force: yes

- name: Apply Configuration
  template:
    src: templates/config.json.j2
    dest: '{{ app_path }}/config.json'

- name: Install packages based on package.json.
  npm:
    path: '{{ app_path }}'

- name: Check pm2
  shell: pm2 ls | grep -q myapp
  register: app_exists
  failed_when: app_exists.rc > 1
  changed_when: false

- name: Delete old pm2 process
  command: pm2 delete myapp
  when: app_exists.rc == 0

- name: Start pm2
  command: pm2 start {{ app_path }}/app.js --name myapp