---
# tasks file for common

- name: Print Hello World
  debug:
    msg: 'Hello MetaNook from {{ ansible_host }}!'
  tags: common

- name: Set System Timezone to Europe/Berlin
  timezone: 
    name: Europe/Berlin
  tags: common