---
# tasks file for dbserver

- name: Print Hello World
  debug:
    msg: '{{ mysql_users }}'

- name: Create user for mysql
  user:
    name: '{{ mysql_user_name }}'

- include_role: 
    name: geerlingguy.mysql

- copy:
    src: files/table.sql
    dest: /tmp

- name: Create Table If Not Existing
  mysql_db:
    name: '{{ database_name }}'
    login_user: '{{ database_user }}'
    login_password: '{{ database_password }}'
    state: import
    target: /tmp/table.sql